name: 07 - expressions
run-name: 07 - expressions | DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}

on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] Print start-up data'
              if: ${{inputs.debug}}
              run: |
                echo "Triggered by: ${{github.event_name}}"
                echo "Branch: ${{github.ref}}"
                echo "Commit SHA: ${{github.sha}}"
                echo "runner OS: ${{runner.os}}"
            - name: '[debug] print triggered my main'
              if: ${{inputs.debug && github.ref == 'refs/heads/main'}} 
              run: echo "I was triggered by main"
            - name: Greeting
              run: echo "Hello world"