name: 10 - Controlling the Execution Flow

on: 
    workflow_dispatch:
        inputs:
            pass-unit-tests:
                type: boolean
                description: unit test pass or not
                default: true

jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: lint and build
              run: echo "lint and build"
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: run unit test
              run: echo "run unit test"
            - name: failing tests
              if: ${{ !inputs.pass-unit-tests}}
              run: exit 1
    deploy-nonprod:
        runs-on: ubuntu-latest
        needs: 
            - lint-build
            - unit-test
        steps:
            - name: deploy to nonprod
              run: echo "deploy nonprod"
    e2e-tests:
        runs-on: ubuntu-latest
        needs: 
            - deploy-nonprod
        steps:
            - name: run e2e test
              run: echo "run e2e test"
    load-tests:
        runs-on: ubuntu-latest
        needs: 
            - deploy-nonprod
        steps:
            - name: run load test
              run: echo "load e2e test"
    deploy-prod:
        runs-on: ubuntu-latest
        needs: 
            - e2e-tests
        steps:
            - name: deploy prod
              run: echo "deploy prod"