name: 15- Matrices

on:
    workflow_dispatch:

jobs:
    backwards-compability:
        name: ${{matrix.os}}-${{matrix.node-version}}
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: true
            matrix:
                node-version: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - windows-latest
                include:
                    - os: ubuntu-latest
                      node-version: 16.x
                    - os: ubuntu-latest
                      node-version: 21.x
                      tag: experimental
        steps:
            - name: Setup node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{matrix.node-version}}
            - name: fail if experimental
              if: matrix.tag == 'experimental'
              run: exit 1
            - name: perform some tests
              run: |
               echo "tests on ${{matrix.os}} and ${{matrix.node-version}}"
               sleep 10
            - name: upload results
              run: echo "test results"
    include-example:
        name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}
        runs-on: ubuntu-latest
        strategy:
          matrix:
            color: [red,green]
            shape: [circle,square]
            size: [small,large]
            include:
              - color: red
                shape: triangle
            exclude:
              - color: green
                shape: circle
        steps:
          - name: dummy
            run: echo "${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}"

